### ISSUE TITLE
Program sees my VM's and starts when type in the VM but when runs it cant find VM

### ISSUE THREAD

**Issue by Mikewins1** [OnePlusOneIsTu/vBoxSysInfoMod-linux#1]
vBoxSysInfoMod-Linux v1.1rc1

Registered VMs:
"win10" {30da7a4f-57f7-4a57-9d8b-42a3bda423b6}
"Scambait7" {d8a55c0f-f7a1-4903-bcd3-b4b7eb4d2ab8}

Which VM would you like to modify? [Last: '']
'q' to quit
>> win10
THEN ENTER and use all the examples.....THEN........

vBoxSysInfoMod-Linux v1.1rc1

Modding the System

Leave values blank for example settings.
System Manufacturer (Default: "LENOVO"): 
System Model (Default: "80SM"): 
BIOS Manufacturer (Default: "American Megatrends Inc."): 
BIOS Version (Default: "F4"): 
Processor Manufacturer (Default: "Intel(R)"): 
Processor Version (Default: "Core(TM) i5"): 

Starting modifications...
Modifying DMI BIOS Information (type 0)...
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
Modifying DMI System Information (type 1)...
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
Modifying DMI Board Information (type 2)...
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
Modifying DMI Processor Information (type 4)...
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
VBoxManage: error: Could not find a registered machine named ''
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 934 of file VBoxManageMisc.cpp
Completed.

Press any key to continue...

**Comment by OnePlusOneIsTu** [comment]
This issue occurred due to variables being used after being cleared at the incorrect time. 
I've updated the repo so please let me know if it happens again, thanks.
